version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: Tom13092003
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: F1API/Dockerfile
    image: formula-one-insight-dashboard-api:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=db;Database=F1DB;User Id=sa;Password=12345;TrustServerCertificate=True;"
    ports:
      - "5000:80"
    depends_on:
      - db

volumes:
  sql_data: