version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: Tom13092003
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: F1API/Dockerfile
    image: formula-one-insight-dashboard-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=F1DB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - Jwt__Key=5b18357f9b011918d9caf82999f19c190f69dfdeeb7933b36098220e9f1f88a9
      - Jwt__Issuer=FormulaOneInsight
      - Jwt__Audience=FormulaOneInsightUsers
    ports:
      - "5000:80"
    depends_on:
      - db

volumes:
  sql_data: